easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
         - App\Entity\User
    site_name: 'Administration des <em style="font-size: 80%;">utilisateurs</em>'
    design:
            brand_color: 'red'
            