<?php
// src/Controller/RegistrationController.php
namespace App\Controller;

use App\Form\FilmType;
use App\Entity\Film;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class FilmController extends Controller
{
    /**
     * @Route("/admin2/film", name="film")
     */
    public function filmAction(Request $request)
    {

        $film = new Film();
        // instancie le formulaire avec les contraintes par défaut, + la contrainte registration pour que la saisie du mot de passe soit obligatoire
        $form = $this->createForm(FilmType::class, $film);


        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {



            $image = $film->getImageFilm();
            $fileName = $this->generateUniqueFileName().'.'.$image->guessExtension();

            try {
                $image->move(
                    $this->getParameter('brochures_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                die("le fichier n'a pas ete uploader veiller verifier svp");
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($film);
            $em->flush();

            //$request->getSession()->getFlashBag()->add('success', "Votre compte est enregistré.");

            return $this->redirectToRoute('easyadmin');
        }

        return $this->render('film/index.html.twig',['form' => $form->createView()]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
